#############################################################
############# Clock and Reset constraints ###################
#############################################################

# Sometime after Vivado 2020, it became impossible to rename an autogenerated clock,
# because it doesn't find pins inside of the OOC MMCM (this makes sense), nor does it
# find the pins of the MMCM instantiation (this does not make sense...). You get a warning
# during synthesis/implementation, but opening the design it renames it in report_clocks...
# Instead, to use in XDC files, use get_clocks -of_objects [get_pins mmcm/clk_logic]
# create_generated_clock -name abcd [get_pins mmcm/clk_logic]
# create_generated_clock -name abcd [mmcm/inst/mmcm_adv_inst/CLKOUT0]

# The external reset signal is asynchronous (mechanical button press), so do not check setup/hold times
set_false_path -from [get_ports i_resetn]

# TODO: think this is super wrong, Vivado thinks it has same period as clk_logic
# Create a random clock to drive 7 segment pins so methodology doesn't warn about no clock
create_generated_clock -name clk_slow -source [get_pins sevenseg/clk_slow_reg/Q] -multiply_by 1 [get_pins sevenseg/clk_slow_reg/Q]

#############################################################
################# IO pin constraints ########################
#############################################################

set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]

# LED timings are not important, so leave fully unconstrained
set_false_path -to [get_ports {o_led[*]}]

# 7 Segment timings not important
set_false_path -to [get_ports {o_seg[*]}]
set_false_path -to [get_ports {o_seg_an[*]}]

# Physical buttons fully unconstrained
set_false_path -from [get_ports i_btnc]

create_waiver -type METHODOLOGY -id {TIMING-17} -user "timm" -desc "Ignore the 7 segment LED clock pins driven by logic" -objects [get_pins {sevenseg/p_strobe.v_index_reg[*]/C}] -timestamp "Sat Nov  1 20:21:48 GMT 2025"
create_waiver -type METHODOLOGY -id {TIMING-17} -user "timm" -desc "Ignore the 7 segment LED clock pins driven by logic" -objects [get_pins {sevenseg/p_strobe.v_strobe_reg[*]/C}] -timestamp "Sat Nov  1 20:25:48 GMT 2025"
create_waiver -type METHODOLOGY -id {TIMING-17} -user "timm" -desc "Ignore the 7 segment LED clock pins driven by logic" -objects [get_pins {sevenseg/o_seg_an_reg[*]/C}] -timestamp "Sat Nov  1 20:26:16 GMT 2025"
create_waiver -type METHODOLOGY -id {TIMING-17} -user "timm" -desc "Ignore the 7 segment LED clock pins driven by logic" -objects [get_pins {sevenseg/o_seg_reg[*]/C}] -timestamp "Sat Nov  1 20:26:24 GMT 2025"
